apiVersion: v2
name: hl7-resource-generator
description: A Helm Chart to deploy the Alvearie HL7 Resource Generator service.  This service will convert HL7 data to FHIR.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 0.0.1

keywords:
  - ibm
  - alvearie
  - hl7
  - fhir

home: https://github.com/Alvearie/hl7-resource-generator-service

maintainers:
  - name: Pushpa Bhallamudi
    email: pbhallam@us.ibm.com
  - name: Adam T. Clark
    email: atclark@us.ibm.com